### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by Walter-Correa** [ThreeKingz/easy-mysql#6]
include\easy-mysql.inc(1116) : error 001: expected token: "-string end-", but found "-identifier-"
include\easy-mysql.inc(1169) : error 001: expected token: "-string end-", but found "-identifier-"

**Line 1116** - handle = SQL::CreateTable(table, (isnull(column_where)) ? "InnoDB" : column_where, (isnull(column_where2)) ? "latin5" : column_where2, connectionHandle);

**Line 1169** - handle = SQL::CreateTable(table, (isnull(column_where)) ? "InnoDB" : column_where, (isnull(column_where2)) ? "latin5" : column_where2, connectionHandle);

**Comment by MaxAndolini** [comment]
@Walter-Correa Did you try v3.8?

**Comment by Walter-Correa** [comment]
> @Walter-Correa Did you try v3.8?

But 3.8 is not in releases list.

**Comment by MaxAndolini** [comment]
> > @Walter-Correa Did you try v3.8?
> 
> But 3.8 is not in releases list.

You're right, now you can look.

**Comment by Walter-Correa** [comment]
> > > @Walter-Correa Did you try v3.8?
> > 
> > 
> > But 3.8 is not in releases list.
> 
> You're right, now you can look.

Thank you. Your include is the best, keep it up!

**Comment by MaxAndolini** [comment]
> > > > @Walter-Correa Did you try v3.8?
> > > 
> > > 
> > > But 3.8 is not in releases list.
> > 
> > 
> > You're right, now you can look.
> 
> Thank you. Your include is the best, keep it up!

Thanks for your comment.

**Comment by Walter-Correa** [comment]
include\easy-mysql.inc(1020) : error 017: undefined symbol "handle"
include\easy-mysql.inc(1018) : warning 203: symbol is never used: "connectionhandle"

**Comment by MaxAndolini** [comment]
> include\easy-mysql.inc(1020) : error 017: undefined symbol "handle"
> include\easy-mysql.inc(1018) : warning 203: symbol is never used: "connectionhandle"

Sorry, updated.
